# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.26
# 

Name:       mapplauncherd-qt

# >> macros
# << macros

Summary:    Application launch boosters for Qt4
Version:    1.0.0
Release:    1
Group:      System/Daemons
License:    LGPLv2+
URL:        https://github.com/nemomobile/mapplauncherd-qt/
Source0:    %{name}-%{version}.tar.bz2
Source100:  mapplauncherd-qt.yaml
Requires:   mapplauncherd >= 4.1.0
Requires:   systemd-user-session-targets
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
BuildRequires:  pkgconfig(QtCore)
BuildRequires:  pkgconfig(QtGui)
BuildRequires:  pkgconfig(QtDeclarative)
BuildRequires:  pkgconfig(x11)
BuildRequires:  mapplauncherd-devel >= 4.1.0

%description
Application launch boosters for Qt4


%package devel
Summary:    Development files for launchable applications
Group:      Development/Tools
Requires:   %{name} = %{version}-%{release}

%description devel
Development files for creating applications that can be launched
using mapplauncherd.


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qmake 

make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake_install

# >> install post
mkdir -p %{buildroot}/usr/lib/systemd/user/user-session.target.wants || true
ln -s ../booster-qt4.service ../booster-qml.service %{buildroot}/usr/lib/systemd/user/user-session.target.wants/
# << install post

%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig

%files
%defattr(-,root,root,-)
%{_libexecdir}/mapplauncherd/booster-qt4
%{_libexecdir}/mapplauncherd/booster-qml
%{_libdir}/libmdeclarativecache.so.*
%{_libdir}/systemd/user/booster-qt4.service
%{_libdir}/systemd/user/user-session.target.wants/booster-qt4.service
%{_libdir}/systemd/user/booster-qml.service
%{_libdir}/systemd/user/user-session.target.wants/booster-qml.service
# >> files
# << files

%files devel
%defattr(-,root,root,-)
%{_datadir}/qt4/mkspecs/features/*.prf
%{_libdir}/pkgconfig/*.pc
%{_libdir}/libmdeclarativecache.so
%{_includedir}/mdeclarativecache/*
# >> files devel
# << files devel
